version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: weather-postgres-dev
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis:7-alpine
    container_name: weather-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: weather-rabbitmq-dev
    environment:
      RABBITMQ_DEFAULT_USER: weather_user
      RABBITMQ_DEFAULT_PASS: weather_password
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data_dev:
  redis_data_dev:
  rabbitmq_data_dev:
